-- (c) Copyright 1995-2025 Xilinx, Inc. All rights reserved.
-- 
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
-- 
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
-- 
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
-- 
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES.
-- 
-- DO NOT MODIFY THIS FILE.

-- IP VLNV: xilinx.com:module_ref:conv_accelerator_wrapper:1.0
-- IP Revision: 1

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY conv_accelerator_bd_conv_accelerator_wra_0_0 IS
  PORT (
    S_AXI_LITE_ACLK : IN STD_LOGIC;
    S_AXI_LITE_ARESETN : IN STD_LOGIC;
    S_AXI_LITE_AWVALID : IN STD_LOGIC;
    S_AXI_LITE_AWREADY : OUT STD_LOGIC;
    S_AXI_LITE_AWADDR : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S_AXI_LITE_AWPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S_AXI_LITE_WVALID : IN STD_LOGIC;
    S_AXI_LITE_WREADY : OUT STD_LOGIC;
    S_AXI_LITE_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S_AXI_LITE_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S_AXI_LITE_BVALID : OUT STD_LOGIC;
    S_AXI_LITE_BREADY : IN STD_LOGIC;
    S_AXI_LITE_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S_AXI_LITE_ARVALID : IN STD_LOGIC;
    S_AXI_LITE_ARREADY : OUT STD_LOGIC;
    S_AXI_LITE_ARADDR : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S_AXI_LITE_ARPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S_AXI_LITE_RVALID : OUT STD_LOGIC;
    S_AXI_LITE_RREADY : IN STD_LOGIC;
    S_AXI_LITE_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S_AXI_LITE_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    BRAM_INPUT_addr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_INPUT_din : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_INPUT_dout : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_INPUT_en : OUT STD_LOGIC;
    BRAM_INPUT_we : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    BRAM_INPUT_rst : OUT STD_LOGIC;
    BRAM_INPUT_clk : OUT STD_LOGIC;
    BRAM_FILTER0_addr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_FILTER0_din : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_FILTER0_dout : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_FILTER0_en : OUT STD_LOGIC;
    BRAM_FILTER0_we : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    BRAM_FILTER0_rst : OUT STD_LOGIC;
    BRAM_FILTER0_clk : OUT STD_LOGIC;
    BRAM_FILTER1_addr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_FILTER1_din : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_FILTER1_dout : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_FILTER1_en : OUT STD_LOGIC;
    BRAM_FILTER1_we : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    BRAM_FILTER1_rst : OUT STD_LOGIC;
    BRAM_FILTER1_clk : OUT STD_LOGIC;
    BRAM_FILTER2_addr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_FILTER2_din : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_FILTER2_dout : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_FILTER2_en : OUT STD_LOGIC;
    BRAM_FILTER2_we : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    BRAM_FILTER2_rst : OUT STD_LOGIC;
    BRAM_FILTER2_clk : OUT STD_LOGIC;
    BRAM_FILTER3_addr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_FILTER3_din : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_FILTER3_dout : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_FILTER3_en : OUT STD_LOGIC;
    BRAM_FILTER3_we : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    BRAM_FILTER3_rst : OUT STD_LOGIC;
    BRAM_FILTER3_clk : OUT STD_LOGIC;
    BRAM_OUTPUT_addr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_OUTPUT_din : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_OUTPUT_dout : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    BRAM_OUTPUT_en : OUT STD_LOGIC;
    BRAM_OUTPUT_we : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    BRAM_OUTPUT_rst : OUT STD_LOGIC;
    BRAM_OUTPUT_clk : OUT STD_LOGIC;
    accelerator_controls_activation_bram : OUT STD_LOGIC;
    swap_activations : OUT STD_LOGIC;
    swap_filters : OUT STD_LOGIC
  );
END conv_accelerator_bd_conv_accelerator_wra_0_0;

ARCHITECTURE conv_accelerator_bd_conv_accelerator_wra_0_0_arch OF conv_accelerator_bd_conv_accelerator_wra_0_0 IS
  ATTRIBUTE DowngradeIPIdentifiedWarnings : STRING;
  ATTRIBUTE DowngradeIPIdentifiedWarnings OF conv_accelerator_bd_conv_accelerator_wra_0_0_arch: ARCHITECTURE IS "yes";
  COMPONENT conv_accelerator_wrapper IS
    GENERIC (
      C_AXI_ADDR_WIDTH : INTEGER;
      C_AXI_DATA_WIDTH : INTEGER;
      DIM_WIDTH : INTEGER;
      INPUT_ADDR_WIDTH : INTEGER;
      FILTER_ADDR_WIDTH : INTEGER;
      OUTPUT_ADDR_WIDTH : INTEGER;
      INPUT_BRAM_ADDR_WIDTH : INTEGER;
      FILTER_BRAM_ADDR_WIDTH : INTEGER;
      OUTPUT_BRAM_ADDR_WIDTH : INTEGER;
      BRAM_DATA_WIDTH : INTEGER;
      MAC_DATA_WIDTH : INTEGER;
      MAC_OUTPUT_DATA_WIDTH : INTEGER
    );
    PORT (
      S_AXI_LITE_ACLK : IN STD_LOGIC;
      S_AXI_LITE_ARESETN : IN STD_LOGIC;
      S_AXI_LITE_AWVALID : IN STD_LOGIC;
      S_AXI_LITE_AWREADY : OUT STD_LOGIC;
      S_AXI_LITE_AWADDR : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S_AXI_LITE_AWPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S_AXI_LITE_WVALID : IN STD_LOGIC;
      S_AXI_LITE_WREADY : OUT STD_LOGIC;
      S_AXI_LITE_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S_AXI_LITE_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S_AXI_LITE_BVALID : OUT STD_LOGIC;
      S_AXI_LITE_BREADY : IN STD_LOGIC;
      S_AXI_LITE_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S_AXI_LITE_ARVALID : IN STD_LOGIC;
      S_AXI_LITE_ARREADY : OUT STD_LOGIC;
      S_AXI_LITE_ARADDR : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S_AXI_LITE_ARPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S_AXI_LITE_RVALID : OUT STD_LOGIC;
      S_AXI_LITE_RREADY : IN STD_LOGIC;
      S_AXI_LITE_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S_AXI_LITE_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      BRAM_INPUT_addr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_INPUT_din : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_INPUT_dout : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_INPUT_en : OUT STD_LOGIC;
      BRAM_INPUT_we : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      BRAM_INPUT_rst : OUT STD_LOGIC;
      BRAM_INPUT_clk : OUT STD_LOGIC;
      BRAM_FILTER0_addr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_FILTER0_din : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_FILTER0_dout : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_FILTER0_en : OUT STD_LOGIC;
      BRAM_FILTER0_we : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      BRAM_FILTER0_rst : OUT STD_LOGIC;
      BRAM_FILTER0_clk : OUT STD_LOGIC;
      BRAM_FILTER1_addr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_FILTER1_din : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_FILTER1_dout : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_FILTER1_en : OUT STD_LOGIC;
      BRAM_FILTER1_we : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      BRAM_FILTER1_rst : OUT STD_LOGIC;
      BRAM_FILTER1_clk : OUT STD_LOGIC;
      BRAM_FILTER2_addr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_FILTER2_din : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_FILTER2_dout : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_FILTER2_en : OUT STD_LOGIC;
      BRAM_FILTER2_we : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      BRAM_FILTER2_rst : OUT STD_LOGIC;
      BRAM_FILTER2_clk : OUT STD_LOGIC;
      BRAM_FILTER3_addr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_FILTER3_din : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_FILTER3_dout : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_FILTER3_en : OUT STD_LOGIC;
      BRAM_FILTER3_we : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      BRAM_FILTER3_rst : OUT STD_LOGIC;
      BRAM_FILTER3_clk : OUT STD_LOGIC;
      BRAM_OUTPUT_addr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_OUTPUT_din : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_OUTPUT_dout : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      BRAM_OUTPUT_en : OUT STD_LOGIC;
      BRAM_OUTPUT_we : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      BRAM_OUTPUT_rst : OUT STD_LOGIC;
      BRAM_OUTPUT_clk : OUT STD_LOGIC;
      accelerator_controls_activation_bram : OUT STD_LOGIC;
      swap_activations : OUT STD_LOGIC;
      swap_filters : OUT STD_LOGIC
    );
  END COMPONENT conv_accelerator_wrapper;
  ATTRIBUTE IP_DEFINITION_SOURCE : STRING;
  ATTRIBUTE IP_DEFINITION_SOURCE OF conv_accelerator_bd_conv_accelerator_wra_0_0_arch: ARCHITECTURE IS "module_ref";
  ATTRIBUTE X_INTERFACE_INFO : STRING;
  ATTRIBUTE X_INTERFACE_PARAMETER : STRING;
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_OUTPUT_clk: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_OUTPUT CLK";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_OUTPUT_rst: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_OUTPUT RST";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_OUTPUT_we: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_OUTPUT WE";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_OUTPUT_en: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_OUTPUT EN";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_OUTPUT_dout: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_OUTPUT DOUT";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_OUTPUT_din: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_OUTPUT DIN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF BRAM_OUTPUT_addr: SIGNAL IS "XIL_INTERFACENAME BRAM_OUTPUT, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_OUTPUT_addr: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_OUTPUT ADDR";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER3_clk: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER3 CLK";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER3_rst: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER3 RST";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER3_we: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER3 WE";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER3_en: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER3 EN";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER3_dout: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER3 DOUT";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER3_din: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER3 DIN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF BRAM_FILTER3_addr: SIGNAL IS "XIL_INTERFACENAME BRAM_FILTER3, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER3_addr: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER3 ADDR";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER2_clk: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER2 CLK";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER2_rst: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER2 RST";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER2_we: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER2 WE";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER2_en: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER2 EN";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER2_dout: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER2 DOUT";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER2_din: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER2 DIN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF BRAM_FILTER2_addr: SIGNAL IS "XIL_INTERFACENAME BRAM_FILTER2, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER2_addr: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER2 ADDR";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER1_clk: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER1 CLK";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER1_rst: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER1 RST";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER1_we: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER1 WE";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER1_en: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER1 EN";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER1_dout: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER1 DOUT";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER1_din: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER1 DIN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF BRAM_FILTER1_addr: SIGNAL IS "XIL_INTERFACENAME BRAM_FILTER1, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER1_addr: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER1 ADDR";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER0_clk: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER0 CLK";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER0_rst: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER0 RST";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER0_we: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER0 WE";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER0_en: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER0 EN";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER0_dout: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER0 DOUT";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER0_din: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER0 DIN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF BRAM_FILTER0_addr: SIGNAL IS "XIL_INTERFACENAME BRAM_FILTER0, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_FILTER0_addr: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_FILTER0 ADDR";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_INPUT_clk: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_INPUT CLK";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_INPUT_rst: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_INPUT RST";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_INPUT_we: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_INPUT WE";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_INPUT_en: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_INPUT EN";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_INPUT_dout: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_INPUT DOUT";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_INPUT_din: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_INPUT DIN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF BRAM_INPUT_addr: SIGNAL IS "XIL_INTERFACENAME BRAM_INPUT, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  ATTRIBUTE X_INTERFACE_INFO OF BRAM_INPUT_addr: SIGNAL IS "xilinx.com:interface:bram:1.0 BRAM_INPUT ADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE AWREADY";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S_AXI_LITE_AWVALID: SIGNAL IS "XIL_INTERFACENAME S_AXI_LITE, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 50000000, ID_WIDTH 0, ADDR_WIDTH 8, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.000, CLK_DOMAIN conv_accelerator_bd_processing_system7_0_0_FCLK_CLK0, N" & 
"UM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_LITE AWVALID";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S_AXI_LITE_ARESETN: SIGNAL IS "XIL_INTERFACENAME S_AXI_LITE_ARESETN, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_ARESETN: SIGNAL IS "xilinx.com:signal:reset:1.0 S_AXI_LITE_ARESETN RST";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S_AXI_LITE_ACLK: SIGNAL IS "XIL_INTERFACENAME S_AXI_LITE_ACLK, ASSOCIATED_BUSIF S_AXI_LITE, ASSOCIATED_RESET S_AXI_LITE_ARESETN, FREQ_HZ 50000000, FREQ_TOLERANCE_HZ 0, PHASE 0.000, CLK_DOMAIN conv_accelerator_bd_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_LITE_ACLK: SIGNAL IS "xilinx.com:signal:clock:1.0 S_AXI_LITE_ACLK CLK";
BEGIN
  U0 : conv_accelerator_wrapper
    GENERIC MAP (
      C_AXI_ADDR_WIDTH => 8,
      C_AXI_DATA_WIDTH => 32,
      DIM_WIDTH => 12,
      INPUT_ADDR_WIDTH => 17,
      FILTER_ADDR_WIDTH => 11,
      OUTPUT_ADDR_WIDTH => 17,
      INPUT_BRAM_ADDR_WIDTH => 15,
      FILTER_BRAM_ADDR_WIDTH => 9,
      OUTPUT_BRAM_ADDR_WIDTH => 15,
      BRAM_DATA_WIDTH => 32,
      MAC_DATA_WIDTH => 8,
      MAC_OUTPUT_DATA_WIDTH => 32
    )
    PORT MAP (
      S_AXI_LITE_ACLK => S_AXI_LITE_ACLK,
      S_AXI_LITE_ARESETN => S_AXI_LITE_ARESETN,
      S_AXI_LITE_AWVALID => S_AXI_LITE_AWVALID,
      S_AXI_LITE_AWREADY => S_AXI_LITE_AWREADY,
      S_AXI_LITE_AWADDR => S_AXI_LITE_AWADDR,
      S_AXI_LITE_AWPROT => S_AXI_LITE_AWPROT,
      S_AXI_LITE_WVALID => S_AXI_LITE_WVALID,
      S_AXI_LITE_WREADY => S_AXI_LITE_WREADY,
      S_AXI_LITE_WDATA => S_AXI_LITE_WDATA,
      S_AXI_LITE_WSTRB => S_AXI_LITE_WSTRB,
      S_AXI_LITE_BVALID => S_AXI_LITE_BVALID,
      S_AXI_LITE_BREADY => S_AXI_LITE_BREADY,
      S_AXI_LITE_BRESP => S_AXI_LITE_BRESP,
      S_AXI_LITE_ARVALID => S_AXI_LITE_ARVALID,
      S_AXI_LITE_ARREADY => S_AXI_LITE_ARREADY,
      S_AXI_LITE_ARADDR => S_AXI_LITE_ARADDR,
      S_AXI_LITE_ARPROT => S_AXI_LITE_ARPROT,
      S_AXI_LITE_RVALID => S_AXI_LITE_RVALID,
      S_AXI_LITE_RREADY => S_AXI_LITE_RREADY,
      S_AXI_LITE_RDATA => S_AXI_LITE_RDATA,
      S_AXI_LITE_RRESP => S_AXI_LITE_RRESP,
      BRAM_INPUT_addr => BRAM_INPUT_addr,
      BRAM_INPUT_din => BRAM_INPUT_din,
      BRAM_INPUT_dout => BRAM_INPUT_dout,
      BRAM_INPUT_en => BRAM_INPUT_en,
      BRAM_INPUT_we => BRAM_INPUT_we,
      BRAM_INPUT_rst => BRAM_INPUT_rst,
      BRAM_INPUT_clk => BRAM_INPUT_clk,
      BRAM_FILTER0_addr => BRAM_FILTER0_addr,
      BRAM_FILTER0_din => BRAM_FILTER0_din,
      BRAM_FILTER0_dout => BRAM_FILTER0_dout,
      BRAM_FILTER0_en => BRAM_FILTER0_en,
      BRAM_FILTER0_we => BRAM_FILTER0_we,
      BRAM_FILTER0_rst => BRAM_FILTER0_rst,
      BRAM_FILTER0_clk => BRAM_FILTER0_clk,
      BRAM_FILTER1_addr => BRAM_FILTER1_addr,
      BRAM_FILTER1_din => BRAM_FILTER1_din,
      BRAM_FILTER1_dout => BRAM_FILTER1_dout,
      BRAM_FILTER1_en => BRAM_FILTER1_en,
      BRAM_FILTER1_we => BRAM_FILTER1_we,
      BRAM_FILTER1_rst => BRAM_FILTER1_rst,
      BRAM_FILTER1_clk => BRAM_FILTER1_clk,
      BRAM_FILTER2_addr => BRAM_FILTER2_addr,
      BRAM_FILTER2_din => BRAM_FILTER2_din,
      BRAM_FILTER2_dout => BRAM_FILTER2_dout,
      BRAM_FILTER2_en => BRAM_FILTER2_en,
      BRAM_FILTER2_we => BRAM_FILTER2_we,
      BRAM_FILTER2_rst => BRAM_FILTER2_rst,
      BRAM_FILTER2_clk => BRAM_FILTER2_clk,
      BRAM_FILTER3_addr => BRAM_FILTER3_addr,
      BRAM_FILTER3_din => BRAM_FILTER3_din,
      BRAM_FILTER3_dout => BRAM_FILTER3_dout,
      BRAM_FILTER3_en => BRAM_FILTER3_en,
      BRAM_FILTER3_we => BRAM_FILTER3_we,
      BRAM_FILTER3_rst => BRAM_FILTER3_rst,
      BRAM_FILTER3_clk => BRAM_FILTER3_clk,
      BRAM_OUTPUT_addr => BRAM_OUTPUT_addr,
      BRAM_OUTPUT_din => BRAM_OUTPUT_din,
      BRAM_OUTPUT_dout => BRAM_OUTPUT_dout,
      BRAM_OUTPUT_en => BRAM_OUTPUT_en,
      BRAM_OUTPUT_we => BRAM_OUTPUT_we,
      BRAM_OUTPUT_rst => BRAM_OUTPUT_rst,
      BRAM_OUTPUT_clk => BRAM_OUTPUT_clk,
      accelerator_controls_activation_bram => accelerator_controls_activation_bram,
      swap_activations => swap_activations,
      swap_filters => swap_filters
    );
END conv_accelerator_bd_conv_accelerator_wra_0_0_arch;
