# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.runs/synth_1/conv_accelerator_bd_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.cache/wt [current_project]
set_property parent.project_path /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/sv_conv_mac.sv
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/sv_dequantization.sv
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/sv_output_storage.sv
}
read_vhdl -library xil_defaultlib {
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/bram_connect.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/bram_switch.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/bram_mux.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/bram_read_delay.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/axis_utils.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/bram_slice_fetcher.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/index_gen.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/mac_stream_provider.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/conv_mac.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/output_storage.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/conv_accelerator.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/conv_config.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/conv_accelerator_wrapper.vhd
  /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/hdl/conv_accelerator_bd_wrapper.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/dequantization.vhd
read_ip -quiet /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/zp_adder/zp_adder.xci

read_ip -quiet /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/mult_q32d0_q0d18/mult_q32d0_q0d18.xci

read_ip -quiet /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/dsp48_custom_mult_add_piped/dsp48_custom_mult_add_piped.xci

add_files /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/conv_accelerator_bd.bd
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_axi_cdma_0_0/conv_accelerator_bd_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_axi_protocol_convert_0_0/conv_accelerator_bd_axi_protocol_convert_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_axi_protocol_convert_3_0/conv_accelerator_bd_axi_protocol_convert_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_0/conv_accelerator_bd_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_0/conv_accelerator_bd_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_1/conv_accelerator_bd_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_1/conv_accelerator_bd_blk_mem_gen_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_2/conv_accelerator_bd_blk_mem_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_2/conv_accelerator_bd_blk_mem_gen_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_3/conv_accelerator_bd_blk_mem_gen_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_3/conv_accelerator_bd_blk_mem_gen_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_4/conv_accelerator_bd_blk_mem_gen_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_4/conv_accelerator_bd_blk_mem_gen_1_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_processing_system7_0_0/conv_accelerator_bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_rst_ps7_0_200M_0/conv_accelerator_bd_rst_ps7_0_200M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/ip/conv_accelerator_bd_rst_ps7_0_200M_0/conv_accelerator_bd_rst_ps7_0_200M_0.xdc]
set_property used_in_implementation false [get_files -all /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/vivado/lab6_temp/lab6_temp.srcs/sources_1/bd/conv_accelerator_bd/conv_accelerator_bd_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/zedboard.xdc
set_property used_in_implementation false [get_files /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/zedboard.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top conv_accelerator_bd_wrapper -part xc7z020clg484-1 -flatten_hierarchy full -directive PerformanceOptimized
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef conv_accelerator_bd_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file conv_accelerator_bd_wrapper_utilization_synth.rpt -pb conv_accelerator_bd_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
