# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/zedboard.xdc

# IP: /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/zp_adder/zp_adder.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zp_adder || ORIG_REF_NAME==zp_adder} -quiet] -quiet

# IP: /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/mult_q32d0_q0d18/mult_q32d0_q0d18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_q32d0_q0d18 || ORIG_REF_NAME==mult_q32d0_q0d18} -quiet] -quiet

# IP: /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/dsp48_custom_mult_add_piped/dsp48_custom_mult_add_piped.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp48_custom_mult_add_piped || ORIG_REF_NAME==dsp48_custom_mult_add_piped} -quiet] -quiet

# Block Designs: bd/conv_accelerator_bd/conv_accelerator_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd || ORIG_REF_NAME==conv_accelerator_bd} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_axi_cdma_0_0/conv_accelerator_bd_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_axi_cdma_0_0 || ORIG_REF_NAME==conv_accelerator_bd_axi_cdma_0_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_axi_crossbar_0_0/conv_accelerator_bd_axi_crossbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_axi_crossbar_0_0 || ORIG_REF_NAME==conv_accelerator_bd_axi_crossbar_0_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_axi_crossbar_1_0/conv_accelerator_bd_axi_crossbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_axi_crossbar_1_0 || ORIG_REF_NAME==conv_accelerator_bd_axi_crossbar_1_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_axi_protocol_convert_0_0/conv_accelerator_bd_axi_protocol_convert_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_axi_protocol_convert_0_0 || ORIG_REF_NAME==conv_accelerator_bd_axi_protocol_convert_0_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_axi_protocol_convert_3_0/conv_accelerator_bd_axi_protocol_convert_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_axi_protocol_convert_3_0 || ORIG_REF_NAME==conv_accelerator_bd_axi_protocol_convert_3_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_axi_bram_ctrl_0/conv_accelerator_bd_axi_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_axi_bram_ctrl_0 || ORIG_REF_NAME==conv_accelerator_bd_axi_bram_ctrl_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_connect_0_0/conv_accelerator_bd_bram_connect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_connect_0_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_connect_0_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_connect_1_0/conv_accelerator_bd_bram_connect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_connect_1_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_connect_1_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_connect_2_0/conv_accelerator_bd_bram_connect_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_connect_2_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_connect_2_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_connect_3_0/conv_accelerator_bd_bram_connect_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_connect_3_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_connect_3_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_connect_4_0/conv_accelerator_bd_bram_connect_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_connect_4_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_connect_4_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_0/conv_accelerator_bd_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_blk_mem_gen_0_0 || ORIG_REF_NAME==conv_accelerator_bd_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_0/conv_accelerator_bd_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_blk_mem_gen_1_0 || ORIG_REF_NAME==conv_accelerator_bd_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_switch_1_0/conv_accelerator_bd_bram_switch_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_switch_1_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_switch_1_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_1/conv_accelerator_bd_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_blk_mem_gen_0_1 || ORIG_REF_NAME==conv_accelerator_bd_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_1/conv_accelerator_bd_blk_mem_gen_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_blk_mem_gen_1_1 || ORIG_REF_NAME==conv_accelerator_bd_blk_mem_gen_1_1} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_switch_1_1/conv_accelerator_bd_bram_switch_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_switch_1_1 || ORIG_REF_NAME==conv_accelerator_bd_bram_switch_1_1} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_2/conv_accelerator_bd_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_blk_mem_gen_0_2 || ORIG_REF_NAME==conv_accelerator_bd_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_2/conv_accelerator_bd_blk_mem_gen_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_blk_mem_gen_1_2 || ORIG_REF_NAME==conv_accelerator_bd_blk_mem_gen_1_2} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_switch_1_2/conv_accelerator_bd_bram_switch_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_switch_1_2 || ORIG_REF_NAME==conv_accelerator_bd_bram_switch_1_2} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_3/conv_accelerator_bd_blk_mem_gen_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_blk_mem_gen_0_3 || ORIG_REF_NAME==conv_accelerator_bd_blk_mem_gen_0_3} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_3/conv_accelerator_bd_blk_mem_gen_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_blk_mem_gen_1_3 || ORIG_REF_NAME==conv_accelerator_bd_blk_mem_gen_1_3} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_switch_1_3/conv_accelerator_bd_bram_switch_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_switch_1_3 || ORIG_REF_NAME==conv_accelerator_bd_bram_switch_1_3} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_4/conv_accelerator_bd_blk_mem_gen_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_blk_mem_gen_0_4 || ORIG_REF_NAME==conv_accelerator_bd_blk_mem_gen_0_4} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_4/conv_accelerator_bd_blk_mem_gen_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_blk_mem_gen_1_4 || ORIG_REF_NAME==conv_accelerator_bd_blk_mem_gen_1_4} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_mux_0_0/conv_accelerator_bd_bram_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_mux_0_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_mux_0_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_mux_1_0/conv_accelerator_bd_bram_mux_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_mux_1_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_mux_1_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_switch_1_4/conv_accelerator_bd_bram_switch_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_switch_1_4 || ORIG_REF_NAME==conv_accelerator_bd_bram_switch_1_4} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_read_delay_0_0/conv_accelerator_bd_bram_read_delay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_read_delay_0_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_read_delay_0_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_read_delay_1_0/conv_accelerator_bd_bram_read_delay_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_read_delay_1_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_read_delay_1_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_read_delay_2_0/conv_accelerator_bd_bram_read_delay_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_read_delay_2_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_read_delay_2_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_read_delay_3_0/conv_accelerator_bd_bram_read_delay_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_read_delay_3_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_read_delay_3_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_read_delay_4_0/conv_accelerator_bd_bram_read_delay_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_read_delay_4_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_read_delay_4_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_bram_read_delay_5_0/conv_accelerator_bd_bram_read_delay_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_bram_read_delay_5_0 || ORIG_REF_NAME==conv_accelerator_bd_bram_read_delay_5_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_conv_accelerator_wra_0_0/conv_accelerator_bd_conv_accelerator_wra_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_conv_accelerator_wra_0_0 || ORIG_REF_NAME==conv_accelerator_bd_conv_accelerator_wra_0_0} -quiet] -quiet

# IP: /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/zp_adder/zp_adder.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zp_adder || ORIG_REF_NAME==zp_adder} -quiet] -quiet

# IP: /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/mult_q32d0_q0d18/mult_q32d0_q0d18.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_q32d0_q0d18 || ORIG_REF_NAME==mult_q32d0_q0d18} -quiet] -quiet

# IP: /home/zfsalti/487/lab3/CprE-487-Lab-3/lab6_temp/hdl/dsp48_custom_mult_add_piped/dsp48_custom_mult_add_piped.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp48_custom_mult_add_piped || ORIG_REF_NAME==dsp48_custom_mult_add_piped} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_processing_system7_0_0/conv_accelerator_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_processing_system7_0_0 || ORIG_REF_NAME==conv_accelerator_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/conv_accelerator_bd/ip/conv_accelerator_bd_rst_ps7_0_200M_0/conv_accelerator_bd_rst_ps7_0_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_rst_ps7_0_200M_0 || ORIG_REF_NAME==conv_accelerator_bd_rst_ps7_0_200M_0} -quiet] -quiet

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_axi_cdma_0_0/conv_accelerator_bd_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_axi_cdma_0_0 || ORIG_REF_NAME==conv_accelerator_bd_axi_cdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_axi_protocol_convert_0_0/conv_accelerator_bd_axi_protocol_convert_0_0_ooc.xdc

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_axi_protocol_convert_3_0/conv_accelerator_bd_axi_protocol_convert_3_0_ooc.xdc

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_0/conv_accelerator_bd_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_0/conv_accelerator_bd_blk_mem_gen_1_0_ooc.xdc

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_1/conv_accelerator_bd_blk_mem_gen_0_1_ooc.xdc

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_1/conv_accelerator_bd_blk_mem_gen_1_1_ooc.xdc

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_2/conv_accelerator_bd_blk_mem_gen_0_2_ooc.xdc

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_2/conv_accelerator_bd_blk_mem_gen_1_2_ooc.xdc

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_3/conv_accelerator_bd_blk_mem_gen_0_3_ooc.xdc

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_3/conv_accelerator_bd_blk_mem_gen_1_3_ooc.xdc

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_0_4/conv_accelerator_bd_blk_mem_gen_0_4_ooc.xdc

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_blk_mem_gen_1_4/conv_accelerator_bd_blk_mem_gen_1_4_ooc.xdc

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_processing_system7_0_0/conv_accelerator_bd_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_processing_system7_0_0 || ORIG_REF_NAME==conv_accelerator_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_rst_ps7_0_200M_0/conv_accelerator_bd_rst_ps7_0_200M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_rst_ps7_0_200M_0 || ORIG_REF_NAME==conv_accelerator_bd_rst_ps7_0_200M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/conv_accelerator_bd/ip/conv_accelerator_bd_rst_ps7_0_200M_0/conv_accelerator_bd_rst_ps7_0_200M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==conv_accelerator_bd_rst_ps7_0_200M_0 || ORIG_REF_NAME==conv_accelerator_bd_rst_ps7_0_200M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/conv_accelerator_bd/conv_accelerator_bd_ooc.xdc
